sudo: false
dist: trusty
language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - "$HOME/.cache"
script:
  - "mvn -DskipITs clean install"
script:
  - "mvn -DskipITs sonar:sonar"
deploy:
  provider: heroku
  api_key:
    secure: "YOUR ENCRYPTED API KEY"
