sudo: false
language: java
jdk: oraclejdk8
cache:
  directories:
  - "$HOME/.cache"
script:
  - jdk_switcher use oraclejdk8
  - "mvn -DskipITs clean install"
script:
   - jdk_switcher use oraclejdk8
  - "mvn -DskipITs sonar:sonar"
