sudo: false
language: java
cache:
  directories:
  - "$HOME/.cache"
  - "$HOME/.m2"
install:
  provider: script
  script: mvn -DskipITs clean install
  skip_cleanup: true
  on:
    tags: true
deploy:
  provider: script
  script: mvn -DskipITs sonar:sonar
  skip_cleanup: true
  on:
    tags: true
