# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Maven@3
      displayName: Install
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean install'
        options: '-DskipITs --settings ./maven/settings.xml clean install'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: true
        sqMavenPluginVersionChoice: 'latest'

    - task: Maven@3
      displayName: Package
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean install'
        options: '-DskipITs --settings ./maven/settings.xml clean package'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: true
        sqMavenPluginVersionChoice: 'latest'
    
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'karlosarr/myshuttle'
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/src/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'karlosarr/myshuttle'
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/src/Dockerfile'
        tags: |
          latest